### ISSUE TITLE
minSdkVersion 18

### ISSUE THREAD

**Issue by nsantacruz** [Doko-Demo-Doa/react-native-shake#10]
I see that the `minSdkVersion` for Android is 18. My app supports SDK 16. Is there a critical reason why 18 was chosen? I read through most of the Android code and could not find any major issues.

**Comment by Doko-Demo-Doa** [comment]
Actually, no. 18 is the minimum version of the app used to test this library in the past, it was kept that way.

Anyway thank you for the concern, I will make it down to 16.
