### ISSUE TITLE
shaked not working on ios when app in background

### ISSUE THREAD

**Issue by roysG** [Doko-Demo-Doa/react-native-shake#13]
I tested react-native-sensors in background and it works, event on screen off!.
But somehow the shake is not detected when the app is in background.

Is there any fix or some hack to suggest?

**Comment by roysG** [comment]
?

**Comment by pvinis** [comment]
I dont think shake detection works in the background in general.

**Comment by roysG** [comment]
shake detection works with accelorators sensors like react-native-sensor, if yes the it should work in background

**Comment by Doko-Demo-Doa** [comment]
Found this after a quick googling:

`https://stackoverflow.com/questions/39342611/listening-to-device-shake-event-on-background-mode`

**Comment by roysG** [comment]
I allow the background mode in my app, the sensors are working in background mode, execpet this library.

What sensors this package is using?

**Comment by roysG** [comment]
Ok i check and you can do it with motion detection with acceleration
