### ISSUE TITLE
DeviceEventEmitter doesn't remove Shake Event

### ISSUE THREAD

**Issue by lutakyn** [Doko-Demo-Doa/react-native-shake#17]
I am using the library in 2 different components. I realized that the shake event is not removed in the removelistener and I have no idea on how to fix that. Especially the 2 shake event listener is the only one remove but still listens to the first one when I am not  in the component. 
Can you try and fix this?

**Comment by Doko-Demo-Doa** [comment]
I have released a new version. Please try 4.0.2.
