### ISSUE TITLE
Event not firing on iOS 12.0 for RN 0.60.4

### ISSUE THREAD

**Issue by biranchi2018** [Doko-Demo-Doa/react-native-shake#18]
The Shake event is not getting triggered in RN 0.60.4

  componentDidMount() {
     RNShake.addEventListener('ShakeEvent',  () => {
      // Your code...
      Alert.alert('Shake', 'Shake event is called...');
    });
 }

**Comment by foubei** [comment]
May I know how you successfully built this package on iOS? because I am getting error `Library not Found RNShakeEvent`

Autolinking on RN 0.60.5

**Comment by Wilvarin** [comment]
> May I know how you successfully built this package on iOS? because I am getting error `Library not Found RNShakeEvent`
> 
> Autolinking on RN 0.60.5

maybe you forgot

`cd ios
pod install`
