### ISSUE TITLE
[iOS] RN 0.60.5 build failed

### ISSUE THREAD

**Issue by foubei** [Doko-Demo-Doa/react-native-shake#19]
I have successfully built this package on Android but fails on iOS. May I know how to successfully install on RN 0.60.5 with autolinking?

Error on xCode: **library not found for RNShakeEvent**

![微信图片_20200119033911](https://user-images.githubusercontent.com/12202571/72669508-5c250e00-3a6d-11ea-96fc-6f10097aa6cc.jpg)

**Comment by junhoyeo** [comment]
You must install pods after installing.
```bash
cd ios/
pod install
cd ..

react-native run-ios
```

**Comment by Doko-Demo-Doa** [comment]
As @junhoyeo pointed. I also updated the readme.
