### ISSUE TITLE
shake detection works in debug build but not for release build - ios

### ISSUE THREAD

**Issue by denniswon** [Doko-Demo-Doa/react-native-shake#28]
hi, thank you for working on this lib.

This lib works great on debug configuration, but for release configuration, detection does not work.
Is it possible to get it working for release config as well?

rn 0.62.2

**Comment by rcidt** [comment]
I am also experiencing the same behavior. Debug mode works, but not release mode.

**Comment by Doko-Demo-Doa** [comment]
Thank you for reporting, I will take a look ASAP.

**Comment by denniswon** [comment]
@Doko-Demo-Doa is there any update on this issue?

**Comment by Doko-Demo-Doa** [comment]
I'm still looking into it. It seems that the old `RCTBridge` is deprecated. I'm going to replace it with new NativeEventEmitter implementation.

**Comment by Doko-Demo-Doa** [comment]
I have released a new version and it should work on both mode. Please try 4.0.2
