### ISSUE TITLE
Too senstive

### ISSUE THREAD

**Issue by leeyuchang** [Doko-Demo-Doa/react-native-shake#30]
Hello, Sir

First of all, Thank you for this npm.
But, I have a little bit problem on it. 
the shake function works out even in very small motion gesture.
Do you have any solution to reduce too much senstive?

Thank you
Yuchang

**Comment by Doko-Demo-Doa** [comment]
Thanks for the feedback. It's on my watch list and I'm trying to figure out a new API to expose it without much breaking changes.

**Comment by tradebulls** [comment]
We are facing some issues with Android. We tried changing MAGNITUDE_THRESHOLD value however, it only works on few devices. For other devices, it's still too sensitive.

**Comment by MotasemAghbar** [comment]
Same issue, any updates?

**Comment by nolife08021** [comment]
facing same issue too.

**Comment by Doko-Demo-Doa** [comment]
#36 should fix this, please check and re-open this issue if needed.
