### ISSUE TITLE
Q - Usage in functional components

### ISSUE THREAD

**Issue by andy-clapham** [Doko-Demo-Doa/react-native-shake#33]
Hi -
Very handy library, thanks!
I'm using the pattern:

```js
 useEffect(() => {
        const subscription = RNShake.addListener(onUndo);
        return () => subscription.remove();
    });
```

is this a valid way to do it, or should I be using removeListener() ... or both?

**Comment by Doko-Demo-Doa** [comment]
This is up now with 5.1.0, you are now able to use it as the code you want above. Thanks for using!

**Comment by andy-clapham** [comment]
Cheers!
