### ISSUE TITLE
removeListener method has been deprecated.

### ISSUE THREAD

**Issue by ppapadatis** [Doko-Demo-Doa/react-native-shake#34]
There is an upstream change, where in react-native@0.65.0 they deprecated the old API in favour of a more terse name, so `removeListener()` became `remove()` ([more information can be found here](https://stackoverflow.com/a/69252029/2890360)).

For React Native projects greater than 0.65.0 version, the following warning is shown in the console:
```
EventEmitter.removeListener('ShakeEvent', ...): Method has been deprecated.
Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`.
```
The problem lies in the implementation of the removeListener method:
```typescript
removeListener: (callback: () => void | undefined) =>
    _eventEmitter.removeListener('ShakeEvent', () => {
      callback?.()
    }),
```

Is this package still maintained to a point where this will change soon?

**Comment by Doko-Demo-Doa** [comment]
This is up now with 5.1.0 release.
