### ISSUE TITLE
5.1.0 Uncaught Error in simulator

### ISSUE THREAD

**Issue by kevincoleman** [Doko-Demo-Doa/react-native-shake#35]
I used your sample code copy/pasta into a RN 0.66.3 app, and fired it up in a simulated iPhone 13 Pro. Got an error, even with the listener doing nothing yet:

```
`new NativeEventEmitter()` requires a non-null argument
```

This doesn’t happen when running it on device.

I don’t have a huge problem testing it on device, but someone who’s testing on lots of different devices probably needs the simulators so they don’t break the bank. Even if it’s not intended to work on a simulator it should really not throw errors and block devs in that regard.

I rolled it back to 3.5.0 and changed my syntax, and things worked. It does complain at me for typings, but oh well!

Thanks for your work on this lib! I have used it more than once, and am grateful.

**Comment by Doko-Demo-Doa** [comment]
Hi @kevincoleman may I ask which version are you using? It's currently at `5.1.0` I believe and you should run `pod install` in `ios` folder after installing the lib to integrate with Xcode.

Or am I missing something?

**Comment by kevincoleman** [comment]
Hello!

The error above occurs in 5.1.0.

After any lib changes I always nuke `node_modules` and `package-lock.json`, reinstall, then nuke `ios/Pods/*` and `Podfile.lock` and run pod install.

This is on the latest MacOS and XCode, pre-M1, targeting a simulated iPhone 13 Pro.

**Comment by BlindDev** [comment]
Having same issue with `5.1.1`

**Comment by Doko-Demo-Doa** [comment]
Hi, I have released a new version. Please check if this problem still persists.

**Comment by pristinejudah** [comment]
I'm also experiencing the same issue in version 5.2.0

**Comment by Doko-Demo-Doa** [comment]
I have fixed this issue, please check. The version is 5.3.0.

**Comment by pristinejudah** [comment]
The version 5.3.0 fixed the issue for me but there seem to be a new issue catching the shake event, cause now the app returns the below error message when I shake an iPhone

```Sending `ShakeEvent` with no listeners registered.```

I've create a different issue to track this 

[https://github.com/Doko-Demo-Doa/react-native-shake/issues/42](https://github.com/Doko-Demo-Doa/react-native-shake/issues/42)
