### ISSUE TITLE
`new NativeEventEmitter()` requires a non-null argument., js engine: hermes  Error

### ISSUE THREAD

**Issue by hasanalicansu** [Doko-Demo-Doa/react-native-shake#40]
Hello 👋

At new version 5.2.0
/react-native-shake/lib/index.js
`const _eventEmitter = new react_native_1.NativeEventEmitter();`

This code line give an error because have forgotten parametre in react_native_1.NativeEventEmitter(). You should have added parametre. 

Code line with parametre 
`const _eventEmitter = new react_native_1.NativeEventEmitter(react_native_1.NativeModules.RNShakeEvent);`

**Comment by Doko-Demo-Doa** [comment]
I have fixed this issue, please check.
