### ISSUE TITLE
Sending `ShakeEvent` with no listeners registered.

### ISSUE THREAD

**Issue by pristinejudah** [Doko-Demo-Doa/react-native-shake#42]
Hi on iOS after a proper install of this module and adding the event listener to a useEffect, whenever I shake the device, I get the below error message

`Sending ShakeEvent with no listeners registered.`

Here's my `useEffect`

```
useEffect(() => {
    // This gets logged
    console.log('catch shake')
    
    const subscription = RNShake.addListener(() => {
      // But this never gets logged on iOS
      console.log('shake shake shake')
      
      shouldInitiateReview('report-problem')
    })

    return () => {
      subscription.remove()
    }
  }, [])
```

**Comment by Doko-Demo-Doa** [comment]
Okay, I think I saw where the problem is. Maybe there is a redundant `RCT_EXPORT_METHOD` somewhere.

**Comment by Doko-Demo-Doa** [comment]
New version is released. I think it may solve your issue.

**Comment by pristinejudah** [comment]
Thanks @Doko-Demo-Doa the new release fixed the issue
