### ISSUE TITLE
Too strict peerDependency

### ISSUE THREAD

**Issue by slaci** [Doko-Demo-Doa/react-native-shake#45]
Hello,

I found that this plugin defines an exact react-native `peerDependency`, currently `0.71.6` as `5.3.2` which prevents me to upgrade to `0.71.7` without changing every npm command to use legacy peer deps or force.

Is there any specific reason to not use like `^0.71` for peer dependency?
Thanks

**Comment by Doko-Demo-Doa** [comment]
New version is released and now it should work.
I'm going to close the issue.
