### ISSUE TITLE
Pod install Failure

### ISSUE THREAD

**Issue by pristinejudah** [Doko-Demo-Doa/react-native-shake#49]
I got the below error when running `Pod install` after install this package.

```
[!] Invalid `Podfile` file: 
[!] Invalid `react-native-shake.podspec` file: undefined method `install_modules_dependencies' for Pod:Module
Did you mean?  install_flipper_dependencies.
```

**Comment by egealpay** [comment]
I am having the same problem

**Comment by hkaras19** [comment]
@pristinejudah were you able to find a solution? Running into the same issue.

**Comment by mattjbrill** [comment]
@pristinejudah @egealpay @hkaras19 

I encountered the same issue. It is the result of the collaborators upgrading the package to support react native 0.71+ (https://github.com/Doko-Demo-Doa/react-native-shake/commit/d780911e9d09f0d68df30159ae9a8fd5b30d0c65#diff-ee358e99d81f6c94e1ee986756e207dad0502e1e954bbc9f6d32f55070e3dc4d).

You can add backwards compatibility by duplicating react-native-async-storage's backwards resolution: https://github.com/react-native-async-storage/async-storage/pull/1004/files

So in this package's [react-native-shake.podspec file](https://github.com/Doko-Demo-Doa/react-native-shake/blob/main/react-native-shake.podspec), replace
```
install_modules_dependencies(s)
```
with
```
if respond_to?(:install_modules_dependencies, true)
    install_modules_dependencies(s)
  else
    s.dependency 'React'
  end
```

If you use [patch-package](https://www.npmjs.com/package/patch-package), you can use a patch similar to this
```
diff --git a/node_modules/react-native-shake/react-native-shake.podspec b/node_modules/react-native-shake/react-native-shake.podspec
index e64c25c..9576916 100644
--- a/node_modules/react-native-shake/react-native-shake.podspec
+++ b/node_modules/react-native-shake/react-native-shake.podspec
@@ -15,5 +15,9 @@ Pod::Spec.new do |s|
   s.source        = { :git => "https://github.com/Doko-Demo-Doa/react-native-shake", :tag => "v#{s.version}" }
   s.source_files  = "ios/**/*.{h,m,mm,swift}"
 
-  install_modules_dependencies(s)
+  if respond_to?(:install_modules_dependencies, true)
+    install_modules_dependencies(s)
+  else
+    s.dependency 'React'
+  end
 end

```

**Comment by mattjbrill** [comment]
Opened a PR for it https://github.com/Doko-Demo-Doa/react-native-shake/pull/54
