### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by rom1k** [Doko-Demo-Doa/react-native-shake#5]
I have tried installing this plugin both from the latest release tag and directly from master branch, I have tried building as a debug and and release apk, tried both on a real device (oneplus 3) but nothing happens when I shake the device. No logs, no alert, no trigger. Any ideas?

I'm using react native 0.57.7 and react 16.6.1
```

componentWillMount() {
    RNShake.addEventListener('ShakeEvent', () => {
   
      console.log('detected 'shake')

      Alert.alert(
        'Test',
        'shake happened',
        [
          { text: 'OK', onPress: () => console.log('OK Pressed') },
        ],
        { cancelable: false }
      )
    });

  }

componentWillUnmount() {

    RNShake.removeEventListener('ShakeEvent')
  }

```

**Comment by Doko-Demo-Doa** [comment]
Hi there, sorry to see you getting troubles.

It will not work on debug mode. In release mode, however, I think the way you "shake" your device may affect its triggering.

For example, on iOS, you can just hold the device and fling it (in one direction). On Android, you may have to move the phone back and forth.

If it still doesn't work, please let me know.

**Comment by rom1k** [comment]
Thanks for your reply. I still can't trigger the shake event on my android device no matter how I shake. This is in release mode.

**Comment by Doko-Demo-Doa** [comment]
Seems fine for me. I'm using Nokia X6 with Android 9:

https://streamable.com/kq52r

**Comment by faizulhadijamil** [comment]
It work perfectly in iOS, but not in android. nothing happen when shake the phone except showing the debug menu

**Comment by Doko-Demo-Doa** [comment]
Well it only works in release mode (as mentioned in README) so...
