### ISSUE TITLE
Breaking android compilation on 5.4.0

### ISSUE THREAD

**Issue by tiagomsmagalhaes** [Doko-Demo-Doa/react-native-shake#50]
I installed this package today. on iOS it works fine but it doesn't build for Android. I've downgraded to the previous version and it works well

```
> Task :react-native-shake:generateCodegenSchemaFromJavaScript FAILED
/dir/node_modules/flow-parser/flow_parser.js:807
throw a}function
^

Error: ENOENT: no such file or directory, lstat '/dir/node_modules/react-native-shake/src'
    at Object.lstatSync (node:fs:1566:3)
    at /dir/node_modules/react-native-codegen/lib/cli/combine/combine-js-to-schema-cli.js:26:10
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/dir/node_modules/react-native-codegen/lib/cli/combine/combine-js-to-schema-cli.js:25:10)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  errno: -2,
  syscall: 'lstat',
  code: 'ENOENT',
  path: '/dir/node_modules/react-native-shake/src'
}

ENOENT: no such file or directory, lstat '/dir/node_modules/react-native-shake/src'

Execution failed for task ':react-native-shake:generateCodegenSchemaFromJavaScript'.
> Process 'command 'node'' finished with non-zero exit value 7
```

**Comment by tiagomsmagalhaes** [comment]
why do I have to hack it? shouldn't work out of the box?

unless this repo became suddenly abandoned just after 5 hours of releasing a minor (or major) release which breaks android functionality

**Comment by thegdznet** [comment]
I had the same error. After reading the error message (Error: ENOENT: no such file or directory, lstat '/dir/node_modules/react-native-shake/src') I just looked onto node_modules/react-native-shake and saw that there no 'src' folder bu that 'lib' folder contains the JS stuff. Making those changes my side works fine.

**Comment by harshbytes9026** [comment]
I am having the same issue. Any updates here?

**Comment by levkovich2806** [comment]
have the same error :(

**Comment by levkovich2806** [comment]
"react-native": "^0.72.3",
"react-native-shake": "^5.4.0",

**Comment by harshbytes9026** [comment]
> Hi!
> 
> Edit node_modules/react-native-shake/package.json and change `"jsSrcsDir": "src"` by `"jsSrcsDir": "lib"` at the end.
> 
> You can use patch-package to create a patch that will be reapplied each time You make a npm/yarn install.

This one works.
Thanks!!

**Comment by levkovich2806** [comment]
> > Hi!
> > Edit node_modules/react-native-shake/package.json and change `"jsSrcsDir": "src"` by `"jsSrcsDir": "lib"` at the end.
> > You can use patch-package to create a patch that will be reapplied each time You make a npm/yarn install.
> 
> This one works. Thanks!!

What you did exactly? Can you write all steps? I mean: change this, after that "yarn" or something else more? Can you write step by step your actions?

**Comment by harshbytes9026** [comment]
> > > Hi!
> > > Edit node_modules/react-native-shake/package.json and change `"jsSrcsDir": "src"` by `"jsSrcsDir": "lib"` at the end.
> > > You can use patch-package to create a patch that will be reapplied each time You make a npm/yarn install.
> > 
> > 
> > This one works. Thanks!!
> 
> What did you exactly? Can you write all steps? I mean: change this, after that "yarn" or something else more? Can you write step by step your actions?



Just go to this path: `node_modules/react-native-shake/package.json`

On line number 71 add this: `"jsSrcsDir": "lib"`.

After that just clean the cache and gradlew and you are good to go!!
