### ISSUE TITLE
react native version Up  plz

### ISSUE THREAD

**Issue by Jiyeopkim** [Doko-Demo-Doa/react-native-shake#55]
Hello,

I found that this plugin defines an exact react-native peerDependency, currently 0.71.6 as 5.5.0 which prevents me to upgrade to 0.72.3 without changing every npm command to use legacy peer deps or force.

Could you please update react-native to the latest version? 

Thanks

**Comment by Doko-Demo-Doa** [comment]
Done. Sorry for (somewhat) late response 😢
