### ISSUE TITLE
Package failed to install on react native version 72.4

### ISSUE THREAD

**Issue by sukhdev9501759261** [Doko-Demo-Doa/react-native-shake#58]
Could not resolve dependency:
ERR! peer react-native@"^0.71.6" from react-native-shake@5.5.0

**Comment by Ravi-TSI** [comment]
Same issue, any help on this

**Comment by massimilianochiodi** [comment]
Uff .. same issue

npm ERR! While resolving: mutuofacile@1.0.0
npm ERR! Found: react-native@0.72.6
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.72.6" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.71.6" from react-native-shake@5.5.2

**Comment by Doko-Demo-Doa** [comment]
Resolved in latest version.
