### ISSUE TITLE
Please update peer dependency for react-native

### ISSUE THREAD

**Issue by whitestranger7** [Doko-Demo-Doa/react-native-shake#59]
There's no reason to be bound to react native 0.71.6 version. Instead, please mark is as >=0.71.6 if you're aiming for the version

**Comment by greulist137** [comment]
Agreed!

**Comment by massimilianochiodi** [comment]
uff... 

npm ERR! While resolving: mutuofacile@1.0.0
npm ERR! Found: react-native@0.72.6
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.72.6" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.71.6" from react-native-shake@5.5.2

Same problem ...

**Comment by Doko-Demo-Doa** [comment]
The issue is resolved in latest version.
