### ISSUE TITLE
Event listener

### ISSUE THREAD

**Issue by pierre-elie** [Doko-Demo-Doa/react-native-shake#6]
When integrating the lib in my app, I used `addEventListener` and `removeEventListener` as I normally do, by passing for both the handler function.

Turns out the handler was triggered unexpectedly when removing the event listener.

After looking at the source code I saw it was on purpose:
https://github.com/Doko-Demo-Doa/react-native-shake/blob/master/index.js#L32

My question is: **What was the intention being calling handler when removing the listener?**

Also, since the listener is set in the lib, one can listen multiple times but remove only the latest listener:

```js
// Subscribe multiple times works
RNShake.addEventListener('ShakeEvent', handlerA)
RNShake.addEventListener('ShakeEvent', handlerB)

// Removing only works for latest listener
// and triggers both handleA and handleB, unexpectedly
RNShake.removeEventListener('ShakeEvent', handlerB)
RNShake.removeEventListener('ShakeEvent', handlerA)

// handleA will still be triggered on shake
```

I guess you wanted to keep the `addEventListener`/`removeEventListener` for compatibility reasons (since `addListener` is preferred now), so what about providing both alternatives, with a twist on the legacy ones to handle multiple listeners?

```js
'use strict';

import React, { DeviceEventEmitter, NativeModules } from 'react-native';
import invariant from 'invariant';

const listeners = new Map();

class RNShake {
  static addListener (type: string, handler: Function) {
    invariant(
      type === 'ShakeEvent',
      'RNShake only supports `ShakeEvent` event'
    );

    return DeviceEventEmitter.addListener('ShakeEvent', handler);
  }
  
  static addEventListener(type: string, handler: Function) {
    invariant(
      type === 'ShakeEvent',
      'RNShake only supports `ShakeEvent` event'
    );

    invariant(
      !listeners.has(handler),
      'Duplicate handler for `ShakeEvent` of RNShake'
    );

    listeners.set(
      handler, 
      DeviceEventEmitter.addListener('ShakeEvent', handler)
    );
  }
  
  static removeEventListener(type: string, handler: Function) {
    invariant(
      type === 'ShakeEvent',
      'RNShake only supports `ShakeEvent` event'
    );

    if (handler) {
      const listener = listeners.get(handler);
      if (listener) {
        listener.remove();
        listeners.delete(handler);
      }
    }
    else {
      // Remove all listeners added via `addEventListener`
      for (const listener of listeners.values()) {
        listener.remove();
      }
      listeners.clear();
    }
  }
};

module.exports = RNShake;
```

**Comment by Doko-Demo-Doa** [comment]
Thank you for pointing it out. I was not aware of this issue before since my needs are pretty simple.

Do you have any idea that can solve this? I will gladly accept the PR.

**Comment by sdlee3** [comment]
Hi any solution for below issue? How to remove all the EventListener not only the latest one?
// Subscribe multiple times works
RNShake.addEventListener('ShakeEvent', handlerA)
RNShake.addEventListener('ShakeEvent', handlerB)

// Removing only works for latest listener
// and triggers both handleA and handleB, unexpectedly
RNShake.removeEventListener('ShakeEvent', handlerB)
RNShake.removeEventListener('ShakeEvent', handlerA)

// handleA will still be triggered on shake

**Comment by Doko-Demo-Doa** [comment]
I have released a new version. Please try 4.0.2. It uses `NativeEventEmitter` under the hood and it should solve your problem.

Sorry for the late response though.
