### ISSUE TITLE
Expo support 

### ISSUE THREAD

**Issue by kouloughli-hemza** [Doko-Demo-Doa/react-native-shake#69]
I beleive there is an expo sdk 50 support for react-native-share,
after running the expo prebuild and then expo run ios to build the app i get the following error:

 #include "Props.h"
> 12 | #include <react/renderer/core/PropsParserContext.h>
     |          ^ 'react/renderer/core/PropsParserContext.h' file not found
  13 | #include <react/renderer/core/propsConversions.h>
  
  im not sure if npm installl is the only thing required to do it.
  is there setup on how to use with expo pease?

**Comment by Doko-Demo-Doa** [comment]
Can you try with latest Expo version (51 as of now I believe)?

**Comment by kouloughli-hemza** [comment]
> Can you try with latest Expo version (51 as of now I believe)?

that will be so complicated for us, since we need lot of changes and few things we use i beleive are not stable on 51

**Comment by Doko-Demo-Doa** [comment]
After some checking, I realized that new codegen mechanism only supports React Native 0.74 and up, while Expo 50 supports 0.73: https://expo.dev/changelog/2024/01-18-sdk-50

So for now, you may try a lower version of this lib, maybe 5.3.2.
