### ISSUE TITLE
sendEvent Error

### ISSUE THREAD

**Issue by JoseIgnacio92** [Doko-Demo-Doa/react-native-shake#7]
Hello, in NShakeEventModule.java is not checking if react-native has started in its entirety.

You should include this improvement so that the application does not stop

![image](https://user-images.githubusercontent.com/19535530/52733456-8b9be280-2fa1-11e9-8af0-c1f822ca2f9a.png)

How to reproduce the error? start the application and immediately shake the phone, which will cause the fall when trying to use the bridge even if you start.

Regards!

**Comment by Doko-Demo-Doa** [comment]
Thank you, @JoseIgnacio92 I have bumped a new version, will be on npm soon.
Sometimes I'm really busy. Please submit a PR and I will gladly accept it after a quick test.
